### Submit Score
PUT {{host}}/api/{{api_version}}/score
Content-Type: application/json
Authorization: Bearer {{dev_api_key}}

{
  "level_id": "level_001",
  "level_version": 1,
  "game_version": "1.0.0+0001-dev",
  "solution": "SGVsbG8gV29ybGQ=",
  "solution_hash": "a703fa6a1ed216a4dd03e71bf6604eb1b349de6005d142547155630478ba585f",
  "scores": {
    "time_ms": 12500,
    "striping": 85,
    "fuel_rem": 750,
    "chal_cum": 3
  }
}

### Submit Score
PUT {{host}}/api/{{api_version}}/score
Content-Type: application/json
Authorization: Bearer Bf00rff45ppEUm9actOzSHpnW8NaQjWtwO460x34CoY=

{
  "level_id": "level_001",
  "level_version": 1,
  "game_version": "0.1.0",
  "scores": {
    "time_ms": 15420,
    "stars": 3
  },
  "solution": "cmVwcm9kdWN0aW9uIHN0ZXBz",
  "solution_hash": "d6dbe6a9b25f15b1daff6fa1b36f0c36b93def2d375dbeab897cfae7c198cc61"
}

### Variables
@host = http://localhost:8080
@api_version = v2
@dev_api_key = dev_key_change_in_production